export { Layout } from './components/Layout'
export { Counter } from './components/Counter'
export { HomePage } from './pages/Home'
export { AboutPage } from './pages/About'
export { PostsPage } from './pages/Posts'
export { PostPage } from './pages/Post'
export { NotFoundPage } from './pages/NotFound'
export { getPosts, getPost, type Post } from './data/posts'
export { defaultRouterOptions } from './router-options'
